// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCKSu78GgA56EDZ4eH0TUU4hYuWkajug',
    appId: '1:159911131292:android:6d83f5ebc05af026ad1559',
    messagingSenderId: '159911131292',
    projectId: 'inside-job-f8677',
    databaseURL: 'https://inside-job-f8677-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inside-job-f8677.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBF42n6vSJcC7eUHiYcKKKBWJWm0C6cQs',
    appId: '1:159911131292:ios:a07d33614c48a37fad1559',
    messagingSenderId: '159911131292',
    projectId: 'inside-job-f8677',
    databaseURL: 'https://inside-job-f8677-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inside-job-f8677.firebasestorage.app',
    iosBundleId: 'com.michi.testApp3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIWdCHtY9ra4KxtWGuUBlN5TB5xutnQAI',
    appId: '1:159911131292:web:fa50927e4473d2b1ad1559',
    messagingSenderId: '159911131292',
    projectId: 'inside-job-f8677',
    authDomain: 'inside-job-f8677.firebaseapp.com',
    databaseURL: 'https://inside-job-f8677-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'inside-job-f8677.firebasestorage.app',
    measurementId: 'G-10K0X02DST',
  );

}